BUCKET_ID: "proven-aviary-224609"
APP_PORT: "8081"
APP_HOST: "http://localhost:8081"
DB_USER: "root"
DB_PASSWORD: "xEF14rxFDPbwtkzw"
DB_SERVER: "localhost"
DB_PORT: "3307"
DB_SCHEMA: "library"
GOOGLE_PROJECT_ID: "proven-aviary-224609"