// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Common is an autogenerated mock type for the Common type
type Common struct {
	mock.Mock
}

// Create provides a mock function with given fields: record
func (_m *Common) Create(record interface{}) error {
	ret := _m.Called(record)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: record
func (_m *Common) Delete(record interface{}) error {
	ret := _m.Called(record)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id, out
func (_m *Common) FindByID(id interface{}, out interface{}) error {
	ret := _m.Called(id, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) error); ok {
		r0 = rf(id, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: record
func (_m *Common) Update(record interface{}) error {
	ret := _m.Called(record)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
