// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/AndrianaY/store/models"

// GoodsRepository is an autogenerated mock type for the GoodsRepository type
type GoodsRepository struct {
	mock.Mock
}

// FindFirstByName provides a mock function with given fields: name, out
func (_m *GoodsRepository) FindFirstByName(name string, out *models.Good) error {
	ret := _m.Called(name, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *models.Good) error); ok {
		r0 = rf(name, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGoods provides a mock function with given fields: out
func (_m *GoodsRepository) GetGoods(out *[]models.Good) (uint, error) {
	ret := _m.Called(out)

	var r0 uint
	if rf, ok := ret.Get(0).(func(*[]models.Good) uint); ok {
		r0 = rf(out)
	} else {
		r0 = ret.Get(0).(uint)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*[]models.Good) error); ok {
		r1 = rf(out)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
