// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Log provides a mock function with given fields: keyvals
func (_m *Logger) Log(keyvals ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, keyvals...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(keyvals...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
